# Generated by Django 4.1.5 on 2023-01-19 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighted_at_datetime', models.DateTimeField()),
                ('location_lat', models.FloatField(max_length=10)),
                ('location_long', models.FloatField(max_length=10)),
                ('notes', models.FloatField(max_length=500)),
                ('posted_on_timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
