# Generated by Django 4.1.5 on 2023-01-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='notes',
            field=models.CharField(max_length=500),
        ),
    ]
