# Generated by Django 4.1.5 on 2023-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_sighting_bird_sighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
